version: v0.7.1-alpha.1

dsn: postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: http://auth.localhost/ory/kratos/public
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1:3000
        - http://localhost:3000
        - http://frontend.localhost
        - http://api.localhost
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Content-Type
        - X-Session-Token
        - Cookie
        - X-CSRF-Token
        # - Set-Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
  admin:
    base_url: http://auth.localhost/ory/kratos/admin

selfservice:
  default_browser_return_url: http://auth.localhost/
  allowed_return_urls:
    - http://127.0.0.1:3000
    - http://localhost:3000
    - http://auth.localhost
    - http://api.localhost
    # - http://frontend.localhost

  methods:
    password:
      enabled: true
    link:
      enabled: true
    # code:
    #   enabled: true

  flows:
    error:
      ui_url: http://auth.localhost/error

    settings:
      ui_url: http://auth.localhost/resetPassword
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://auth.localhost/recovery
      # use: code

    verification:
      enabled: true
      ui_url: http://auth.localhost/verification
      after:
        default_browser_return_url: http://auth.localhost/profile

    logout:
      after:
        default_browser_return_url: http://auth.localhost/login

    login:
      ui_url: http://auth.localhost/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://auth.localhost/register
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true