-
  id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://127.0.0.1:4433"
    strip_path: /.ory/kratos/public
  match:
    url: "http://127.0.0.1:4455/.ory/kratos/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    -
      handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

-
  id: "ory:frontend:anonymous"
  upstream:
    preserve_host: true
    url: "http://127.0.0.1:3000"
  match:
    url: "http://127.0.0.1:4455/<{error,recovery,verify,auth/*,**.css,**.js}{/,}>"
    methods:
      - GET
  authenticators:
    -
      handler: anonymous
  authorizer:
    handler: allow
  mutators:
    -
      handler: noop

-
  id: "ory:frontend:protected"
  upstream:
    preserve_host: true
    url: "http://127.0.0.1:3000"
  match:
    url: "http://127.0.0.1:4455/<{,debug,dashboard,settings}>"
    methods:
      - GET
  authenticators:
    -
      handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:4455/auth/login