-
  id: "ory:whoami:anonymous"
  match:
    url: "http://auth.localhost<{/,whoami}>"
    methods:
      - GET
  authenticators:
    -
      handler: anonymous
  authorizer:
    handler: allow
  mutators:
    -
      handler: noop

-
  id: "ory:api-bye:anonymous"
  match:
    url: "http://api.localhost/<{bye}>"
    methods:
      - GET
  authenticators:
    -
      handler: anonymous
  authorizer:
    handler: allow
  mutators:
    -
      handler: noop

  # authenticators:
  #   -
  #     handler: cookie_session
  # authorizer:
  #   handler: allow
  mutators:
    - handler: id_token

-
  id: "ory:frontend:anonymous"
  match:
    url: "http://auth.localhost/<{error,recovery*,verify*,login*,resetPassword*,profile*,**.css,**.js}>"
    methods:
      - GET
      - POST
  authenticators:
    -
      handler: anonymous
  authorizer:
    handler: allow
  mutators:
    -
      handler: noop

-
  id: "ory:frontend:protected"
  match:
    url: "<{https,http}>://auth.localhost/<{dashboard,settings,robots.txt}>"
    methods:
      - GET
      - POST
  authenticators:
    -
      handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token