-
  id: "ory:whoami:anonymous"
  upstream:
    url: "http://auth.localhost/whoami"
    strip_path: /whoami
    preserve_host: true
  match:
    url: "<{https,http}>://auth.localhost<{/,**}>"
    methods:
      - GET
  authenticators:
    -
      handler: anonymous
  authorizer:
    handler: allow
  mutators:
    -
      handler: noop

-
  id: "ory:frontend:anonymous"
  match:
    url: "<{https,http}>://auth.localhost<{/,error,recovery*,verify*,login*,resetPassword*,**.css,**.js}>"
    methods:
      - GET
      - POST
  authenticators:
    -
      handler: anonymous
  authorizer:
    handler: allow
  mutators:
    -
      handler: noop

-
  id: "ory:frontend:protected"
  match:
    url: "http://auth.localhost<{/,dashboard,settings,profile,robots.txt}>"
    methods:
      - GET
      - POST
  authenticators:
    -
      handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token