serve:
  proxy:
    port: 4455 # run the proxy at port 4455
    # cors:
    #   enabled: true
    #   allowed_origins:
    #     - "*"
    #   allowed_methods:
    #     - POST
    #     - GET
    #     - PUT
    #     - PATCH
    #     - DELETE
    #   allowed_headers:
    #     - Authorization
    #     - Content-Type
    #   exposed_headers:
    #     - Content-Type
    #   allow_credentials: true
    #   debug: true
  api:
    port: 4456 # run the api at port 4456
    # cors:
    #   enabled: true
    #   allowed_origins:
    #     - "*"
    #   allowed_methods:
    #     - POST
    #     - GET
    #     - PUT
    #     - PATCH
    #     - DELETE
    #   allowed_headers:
    #     - Authorization
    #     - Content-Type
    #   exposed_headers:
    #     - Content-Type
    #   allow_credentials: true
    #   debug: true

log:
  level: trace
  format: json
  leak_sensitive_values: true

access_rules:
  # matching_strategy: regexp
  # repositories:
  #   - file:///etc/config/oathkeeper/access-rules.json
  matching_strategy: glob
  repositories:
    - file:///etc/config/oathkeeper/access-rules.yml

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: http://auth.localhost/login
        when:
          -
            error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html
                  - application/json

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: http://auth.localhost/ory/oathkeeper/
      # issuer_url: http://oathkeeper:4456/
      jwks_url: file:///etc/config/oathkeeper/id_token.jwks.json
      claims: |
        {
          "session": {{ .Extra | toJson }}
        }

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
  
  noop:
    enabled: true
  
  cookie_session:
    enabled: true
    config:
      check_session_url: http://auth.localhost/ory/kratos/public/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session